title = "Mini Blog"
organization = "DAXA Studio 2024-2025"
record_number = "Record Number"
app_port = 3000
log_level = "info"

[author]
title = "About Me"
description = [
  "Description 1",
  "Description 2",
  "Description 3",
]